### ISSUE TITLE
Code does not work with current okta auth.

### ISSUE THREAD

**Issue by cdberkstresser** [oktadeveloper/okta-php-core-login-example#1]
1. index.php is missing requires for the OktaApiService and UserController.
1. OktaApiService is missing the state request.

**Comment by aaronpk** [comment]
Did you run `composer install`? That should set up the autoload files to bring in the `OktaApiService` and `UserController`.

**Comment by aaronpk** [comment]
For the paper trail, this ended up being an error in the repo because of mixed case filesystems. Fixed [here](https://github.com/oktadeveloper/okta-php-core-login-example/commit/5adecfb143908c13e40a451deb94e50a2e445c87) and [here](https://github.com/oktadeveloper/okta-php-core-login-example/commit/acec959891e0abdb3d483c708a8ca7d35e05d8a5)
